config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :player_characters do
  end

  root "player_characters#index"

end

app/models/alignment.rb
class Alignment < ApplicationRecord
  has_many :player_characters

  validates_presence_of :name, :description
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bond.rb
class Bond < ApplicationRecord
  has_many :class_bonds
end

app/models/class_bond.rb
class ClassBond < ApplicationRecord
  belongs_to :player_character
  belongs_to :bond
end

app/models/class_move.rb
class ClassMove < ApplicationRecord
  belongs_to :player_character
  belongs_to :move
end

app/models/gear.rb
class Gear < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :starting_items
end

app/models/move.rb
class Move < ApplicationRecord
  has_many :class_moves
end

app/models/player_character.rb
class PlayerCharacter < ApplicationRecord
  belongs_to :race
  belongs_to :alignment

  has_many :starting_items
  has_many :items, through: :starting_items
  has_many :class_moves
  has_many :moves, through: :class_moves
  has_many :class_bonds
  has_many :bonds, through: :class_bonds

  accepts_nested_attributes_for :items, :moves, :race, :alignment, :bonds, allow_destroy: true

  validates_presence_of :name, :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma, :class_name

  validates_each :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma do |player_character, attr, value|
    value = 0 if value == nil
    player_character.errors.add(attr, 'must be more than 0 and less then 19') if value > 18 || value < 1
  end

  # validate :total_ability_score

  def str_mod
    mod(self.strength)
  end

  def dex_mod
    mod(self.dexterity)
  end

  def con_mod
    mod(self.constitution)
  end

  def int_mod
    mod(self.intelligence)
  end

  def wis_mod
    mod(self.wisdom)
  end

  def cha_mod
    mod(self.charisma)
  end

  def hit_points
    self.constitution + self.hp_mod
  end
  # 
  # def load
  #   self.load_mod + self.strength
  # end

  private

  def mod(attribute)
    case attribute
    when 1, 2, 3 then -3
    when 4, 5 then -2
    when 6, 7, 8 then -1
    when 9, 10, 11, 12 then 0
    when 13, 14, 15 then 1
    when 16, 17 then 2
    when 18 then 3
    end
  end

  # def total_ability_score
  #   total_score = check_nil("strength") + check_nil("dexterity") + check_nil("constitution") + check_nil("intelligence") + check_nil("wisdom") + check_nil("charisma")
  #   self.errors.add(:ability_score, "should equal #{72 + self.level}") if total_score > 72 + self.level
  # end

  def check_nil(ability)
    self.send("#{ability}=", 0) if self.send(ability) == nil
    self.send(ability)
  end

end

app/models/race.rb
class Race < ApplicationRecord
  has_many :player_characters

  validates_presence_of :name, :description
end

app/models/starting_gear.rb
class StartingGear < ApplicationRecord
  belongs_to :character_class
  belongs_to :gear
end

app/models/starting_item.rb
class StartingItem < ApplicationRecord
  belongs_to :player_character
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/player_character_controller.rb
class PlayerCharacterController < ApplicationController

  def index
    @player_characters = PlayerCharacter.all
  end

  def show
    @player_character = PlayerCharacter.find(:id)
  end

  def new
    @player_character = PlayerCharacter.new
  end

  def create
    @player_character = PlayerCharacter.new(player_character_params)
  end

  def edit
    @player_character = PlayerCharacter.find(:id)
  end

  def update
  end

  private

  def player_character_params
    params.require(:pc).permit(:name, :level, :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma)
  end

end

app/controllers/player_characters_controller.rb
class PlayerCharactersController < ApplicationController

  def index
    @player_characters = PlayerCharacter.all
  end

  def show
    @player_character = PlayerCharacter.includes(:alignment, :race, :moves, :bonds).where(id: params[:id]).first
  end

  def new
    @player_character = PlayerCharacter.new
    @race = @player_character.build_race
    @alignment = @player_character.build_alignment
  end

  def create
    @player_character = PlayerCharacter.new(player_character_params)
    add_moves
    add_bonds
    if @player_character.save
      redirect_to @player_character
    else
      @errors = @player_character
      render "new"
    end
  end

  def edit
    @player_character = PlayerCharacter.includes(:alignment, :race, :moves, :bonds).where(id: params[:id]).first
  end

  def update
  end

  private

  def player_character_params
    params.require(:player_character).permit(:name, :description, :class, :load_mod, :level, :class_name, :hp_mod, :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma, race_attributes: [:name, :description], alignment_attributes: [:name, :description])
  end

  def add_moves
    if params[:moves]
      params[:moves].each do |number, data|
        @player_character.moves << Move.new(name: data[:name], description: data[:description]) unless data[:description] == "" || data[:name] == ""
      end
    end
  end

  def add_bonds
    if params[:bonds]
      params[:bonds].each do |number, data|
        @player_character.bonds << Bond.new(description: data[:description]) unless data[:description] == ""
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DwManager</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/player_characters/index.html.erb
<ul>
<% @player_characters.each do |pc| %>
  <li>
  <%= link_to "#{pc.name}", player_character_path(pc) %>
  </li>
<% end %>
</ul>

app/views/player_characters/new.html.erb
<%= render 'shared/errors', active_object: @errors %>
<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content">
        <%= form_for @player_character do |f| %>
        <div class="row">
          <div class="col s12">
            <%= f.label "Name" %>
            <div class="input-field inline">
              <%= f.text_field :name, placeholder: "Character Name", class: "form-control" %>
            </div>
            <%= f.label "Class"%>
            <%= f.text_field :class_name, placeholder: "Class Name" %>

            <%= f.label "Character Description" %>
            <%= f.text_area :description, placeholder: "Enter a physical description of your character" %>

            <%= f.label "HP Modifier" %>
            <%= f.number_field :hp_mod, in: 4..10, step: 2 %>

            <%= f.label "Load Modifier" %>
            <%= f.number_field :load_mod, in: 6..10, step: 1, value: 6 %>
          </div>

        </div>

        <div class="row stats">

          <div class="col s1">
            <%= f.label "STR" %>
            <%= f.number_field :strength, in: 1..18, step: 1, value: 10 %>
          </div>

          <div class="col s1">
            <%= f.label "DEX" %>
            <%= f.number_field :dexterity, in: 1..18, step: 1, value: 10 %>
          </div>

          <div class="col s1">
            <%= f.label "CON" %>
            <%= f.number_field :constitution, in: 1..18, step: 1, value: 10 %>
          </div>

          <div class="col s1">
            <%= f.label "INT" %>
            <%= f.number_field :intelligence, in: 1..18, step: 1, value: 10 %>
          </div>

          <div class="col s1">
            <%= f.label "WIS" %>
            <%= f.number_field :wisdom, in: 1..18, step: 1, value: 10 %>
          </div>

          <div class="col s1">
            <%= f.label "CHA" %>
            <%= f.number_field :charisma, in: 1..18, step: 1, value: 10 %>
          </div>
        </div>

        <div class="row">


        </div>

        <div class="row">
          <div class="col s12">
            <%= f.fields_for :race do |t| %>
            <%= t.label "Race" %>
            <%= t.text_field :name, placeholder: "Race Name" %>
            <%= t.label "Description" %>
            <%= t.text_area :description, placeholder: "Race Description", class: "form-control"%>
            <% end %>

          </div>

        </div>

        <div class="row">
          <div class="col s12">
            <%= f.fields_for :alignment do |t| %>
            <%= t.label "Alignment" %>
            <%= t.text_field :name, placeholder: "Alignment Name" %>
            <%= t.label "Description" %>
            <%= t.text_area :description, placeholder: "Alignment Description", class: "form-control"%>
            <% end %>

          </div>

        </div>

        <div class="row">
          <div class="col s12">
            <div class="moves-input">
              <% if params[:moves] && params[:moves][:"1"][:name] != "" && params[:moves][:"1"][:description] != ""%>
                <% params[:moves].each do |move_num| %>
              <% else %>
                <input type="text" name="moves[1][name]" placeholder="Move Name" class="moves-name">
                <textarea name="moves[1][description]" placeholder="Description of Move" class="moves-description form-control"></textarea>
              <% end %>
            </div>
          </div>

          <div class="col s12">
            <div class="btn moves-button">
              Add Move
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col s12">
            <div class="bonds-input">
              <% if params[:bonds] && params[:bonds][:"1"][:description] != "" %>
                <% params[:bonds].each do |bond, description| %>
                  <% if description[:description] != "" %>
                    <textarea name=<%= "bonds[#{bond}][description]" %> class="bond-description form-control"><%= "#{description[:description]}" %></textarea>
                  <% end %>
                <% end %>
              <% else %>
                <textarea name="bonds[1][description]" placeholder="Description of Bond" class="bond-description  form-control"></textarea>
              <% end %>
            </div>
          </div>

          <div class="col s12">
            <div class="btn bonds-button">
              Add Bond
            </div>
          </div>
        </div>

      <%= f.submit "Create Character", class: "btn" %>
      <% end %>

      </div>
    </div>
  </div>
</div>

app/views/player_characters/show.html.erb
<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content">
        <h4>Character Name: <%= @player_character.name %></h4>

      </div>

    </div>

  </div>
</div>
<%= "LVL: #{@player_character.level}" %>
<%= "STR: #{@player_character.strength}" %>
<%= @player_character.str_mod %>
<%= "DEX: #{@player_character.dexterity}" %>
<%= @player_character.dex_mod %>
<%= "CON: #{@player_character.constitution}" %>
<%= @player_character.con_mod %>
<%= "INT: #{@player_character.intelligence}" %>
<%= @player_character.int_mod %>
<%= "WIS: #{@player_character.wisdom}" %>
<%= @player_character.wis_mod %>
<%= "CHA: #{@player_character.charisma}" %>
<%= @player_character.cha_mod %>

<%= @player_character.class_name %>
<% if @player_character.description %>
  <%= @player_character.description %>
<% end %>

<%= @player_character.hit_points %>
<%# @player_character.load %>

<%= @player_character.race.name %>
<%= @player_character.race.description %>
<%= @player_character.alignment.name %>
<%= @player_character.alignment.description %>

<% @player_character.moves.each do |move| %>
  <ul>
    <li>
      <b><%= move.name %></b>
    </li>
    <li>
      <%= move.description %>
    </li>
  </ul>
<% end %>

<% @player_character.bonds.each do |bond| %>
  <ul>
    <li>
      <%= bond.description %>
    </li>
  </ul>
<% end %>

app/views/player_characters/test.html.erb
Yo!

app/views/shared/_errors.html.erb
<% if active_object && active_object.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% active_object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>